// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM-7S4Eh-U37vabECa8UuxKrdpvJBkyw4',
    appId: '1:376964098622:web:8ca51f480c9c812060bf6f',
    messagingSenderId: '376964098622',
    projectId: 'mediscan222',
    authDomain: 'mediscan222.firebaseapp.com',
    storageBucket: 'mediscan222.firebasestorage.app',
    measurementId: 'G-EZ004KX18X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC_5-joVnwdQeVKXlx2vQnY5Ua0H2En08',
    appId: '1:376964098622:android:cfa6d34fd5bb30c460bf6f',
    messagingSenderId: '376964098622',
    projectId: 'mediscan222',
    storageBucket: 'mediscan222.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM-7S4Eh-U37vabECa8UuxKrdpvJBkyw4',
    appId: '1:376964098622:web:7973d4d5240df24660bf6f',
    messagingSenderId: '376964098622',
    projectId: 'mediscan222',
    authDomain: 'mediscan222.firebaseapp.com',
    storageBucket: 'mediscan222.firebasestorage.app',
    measurementId: 'G-20XXCREYDD',
  );
}
